<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mercury_controller</name>
  <version>0.0.0</version>
  <description>ROS2 control system for the Mercury stack </description>
  <maintainer email="darnley.6@osu.edu">John Darnley</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- MSG deps -->
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>mercury_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_geometry_msgs</depend>

  <!-- ROS deps -->
  <depend>rclcpp</depend>
  <depend>rcl_interfaces</depend>
  <depend>rclpy</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <!-- Other deps -->
  <depend>yaml-cpp</depend>
  <depend>eigen3_cmake_module</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
